import { SessionProvider } from "next-auth/react";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Lora } from "next/font/google";
import "../globals.css";
import Container from "../components/container/Container";
import Header from "../components/Header";
import Footer from "../components/Footer";
import LayoutClient from "../components/auth/LayoutClient";
import Providers from "../providers";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lora.className} antialiased`}>
        <SessionProvider>
          <Providers>
            <main>
              <Container>
                <LayoutClient>{children}</LayoutClient>
              </Container>
            </main>
            <Toaster position="top-right" reverseOrder={false} />
          </Providers>
        </SessionProvider>
      </body>
    </html>
  );
}
