import { Metadata } from "next";
import { Geist, Geist_Mono, Lora } from "next/font/google";
import "../globals.css";

import LayoutClient from "../components/auth/LayoutClient";
import { Toaster } from "react-hot-toast"; // Import the Toaster component

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lora.className} antialiased`}>
        <LayoutClient>{children}</LayoutClient>

        {/* Add the Toaster component to show toasts */}
        <Toaster position="top-right" reverseOrder={false} />
      </body>
    </html>
  );
}
